/**
 * Settings IA registry — single source for nav, page tabs, and search jump targets.
 *
 * Rules (see docs/llm-wiki/settings-ia.md):
 * - Every user-visible setting must be registered here.
 * - Search matches labelKey + descKeys + keywords (en + active locale via createT).
 * - Deep links: #/settings/{section}[/{tab}]
 */

import type { MessageKey } from "@/i18n";

export type SettingsSectionId =
  | "general"
  | "appearance"
  | "account"
  | "archived"
  | "extensions"
  | "remote_im"
  | "runtime"
  | "shortcuts"
  | "about";

export const SETTINGS_SECTION_IDS: readonly SettingsSectionId[] = [
  "general",
  "appearance",
  "account",
  "archived",
  "extensions",
  "runtime",
  "remote_im",
  "shortcuts",
  "about",
] as const;

export function isSettingsSectionId(v: string | undefined | null): v is SettingsSectionId {
  return !!v && (SETTINGS_SECTION_IDS as readonly string[]).includes(v);
}

/** Page-local tab ids (stable for hash + registry). */
export type SettingsTabId =
  // general
  | "composer"
  | "permissions"
  | "agent"
  | "app"
  // appearance
  | "theme"
  | "interface"
  // account
  | "official"
  | "providers"
  | "extras"
  // extensions
  | "plugins"
  | "skills"
  | "mcp"
  | "agents"
  | "hooks"
  | "market"
  // runtime
  | "cli"
  | "connection"
  | "network"
  | "pool"
  | "tools"
  | "privacy"
  // remote control (section id stays remote_im)
  | "im"
  | "mirror";

export type SettingsNavGroup = "personal" | "system";

export type SettingsNavIcon =
  | "settings"
  | "appearance"
  | "user"
  | "archive"
  | "extensions"
  | "remote_im"
  | "doctor"
  | "keyboard"
  | "info";

export type SettingsTabDef = {
  id: SettingsTabId;
  labelKey: MessageKey;
};

export type SettingsNavDef = {
  id: SettingsSectionId;
  icon: SettingsNavIcon;
  labelKey: MessageKey;
  group: SettingsNavGroup;
  /** Ordered tabs for this section; empty = single-page (no tab strip). */
  tabs: readonly SettingsTabDef[];
  defaultTab?: SettingsTabId;
};

/**
 * One searchable / jumpable settings surface.
 * Prefer registering each control (or cohesive card) with a stable id + anchor.
 */
export type SettingsEntry = {
  /** Stable id, e.g. `general.language` */
  id: string;
  section: SettingsSectionId;
  /** Page tab when the section uses tabs. */
  tab?: SettingsTabId;
  /** DOM id for scrollIntoView (must match element id=). */
  anchorId: string;
  labelKey: MessageKey;
  /** Extra i18n keys included in search (descriptions, option labels). */
  descKeys?: readonly MessageKey[];
  /** Free-form aliases (usually English) for search. */
  keywords?: readonly string[];
};

/** Primary nav order (exactly one row per section — no duplicate runtime). */
export const SETTINGS_NAV: readonly SettingsNavDef[] = [
  {
    id: "general",
    icon: "settings",
    labelKey: "settings.nav.general",
    group: "personal",
    defaultTab: "composer",
    tabs: [
      { id: "composer", labelKey: "settings.tab.composer" },
      { id: "permissions", labelKey: "settings.tab.permissions" },
      { id: "agent", labelKey: "settings.tab.agent" },
      { id: "app", labelKey: "settings.tab.app" },
    ],
  },
  {
    id: "appearance",
    icon: "appearance",
    labelKey: "settings.nav.appearance",
    group: "personal",
    defaultTab: "theme",
    tabs: [
      { id: "theme", labelKey: "settings.tab.theme" },
      { id: "interface", labelKey: "settings.tab.interface" },
    ],
  },
  {
    id: "account",
    icon: "user",
    labelKey: "settings.nav.account",
    group: "personal",
    defaultTab: "official",
    tabs: [
      { id: "official", labelKey: "settings.tabOfficial" },
      { id: "providers", labelKey: "settings.tabProviders" },
      { id: "extras", labelKey: "settings.tabExtras" },
    ],
  },
  {
    id: "archived",
    icon: "archive",
    labelKey: "settings.nav.archived",
    group: "personal",
    tabs: [],
  },
  {
    id: "extensions",
    icon: "extensions",
    labelKey: "settings.nav.extensions",
    group: "system",
    defaultTab: "plugins",
    tabs: [
      { id: "plugins", labelKey: "ext.plugins.title" },
      { id: "skills", labelKey: "ext.skills.title" },
      { id: "mcp", labelKey: "ext.mcp.title" },
      { id: "agents", labelKey: "ext.agents.title" },
      { id: "hooks", labelKey: "ext.hooks.title" },
      { id: "market", labelKey: "ext.market.title" },
    ],
  },
  {
    id: "runtime",
    icon: "doctor",
    labelKey: "settings.nav.runtime",
    group: "system",
    defaultTab: "cli",
    tabs: [
      { id: "cli", labelKey: "settings.tab.cli" },
      { id: "connection", labelKey: "settings.tab.connection" },
      { id: "network", labelKey: "settings.tab.network" },
      { id: "pool", labelKey: "settings.tab.pool" },
      { id: "tools", labelKey: "settings.tab.tools" },
      { id: "privacy", labelKey: "settings.tab.privacy" },
    ],
  },
  {
    id: "remote_im",
    icon: "remote_im",
    labelKey: "settings.nav.remoteIm",
    group: "system",
    defaultTab: "im",
    tabs: [
      { id: "im", labelKey: "settings.tab.remoteIm" },
      { id: "mirror", labelKey: "settings.tab.phoneMirror" },
    ],
  },
  {
    id: "shortcuts",
    icon: "keyboard",
    labelKey: "settings.nav.shortcuts",
    group: "system",
    tabs: [],
  },
  {
    id: "about",
    icon: "info",
    labelKey: "settings.nav.about",
    group: "system",
    tabs: [],
  },
];

/** Full registry of searchable settings (UI rows / cards). */
export const SETTINGS_ENTRIES: readonly SettingsEntry[] = [
  // ── general / composer ──
  {
    id: "general.prefsScope",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-prefsScope",
    labelKey: "settings.prefsScope",
    descKeys: [
      "settings.prefsScopeDesc",
      "settings.prefsScope.global",
      "settings.prefsScope.project",
      "settings.prefsScope.session",
      "settings.section.composer",
    ],
    keywords: ["composer", "prefs", "scope"],
  },
  {
    id: "general.availableModels",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-availableModels",
    labelKey: "settings.availableModels",
    descKeys: ["settings.availableModelsDesc"],
    keywords: ["models", "model list"],
  },
  {
    id: "general.composerMinRows",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerMinRows",
    labelKey: "settings.composerMinRows",
    descKeys: [
      "settings.composerMinRowsDesc",
      "settings.composerMinRows.2",
      "settings.composerMinRows.3",
      "settings.composerMinRows.5",
      "settings.composerMinRows.8",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "height",
      "min height",
      "minimum height",
      "rows",
      "input size",
      "textarea",
      "输入框高度",
      "輸入框高度",
      "最小高度",
      "行数",
      "行數",
    ],
  },
  {
    id: "general.composerSendKey",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerSendKey",
    labelKey: "settings.composerSendKey",
    descKeys: [
      "settings.composerSendKeyDesc",
      "settings.composerSendKey.enter",
      "settings.composerSendKey.modEnter",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "send",
      "enter",
      "mod-enter",
      "cmd enter",
      "ctrl enter",
      "newline",
      "keyboard",
    ],
  },
  {
    id: "general.composerSpellcheck",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerSpellcheck",
    labelKey: "settings.composerSpellcheck",
    descKeys: [
      "settings.composerSpellcheckDesc",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "spellcheck",
      "spell check",
      "spelling",
      "typo",
      "autocorrect",
    ],
  },
  {
    id: "general.composerDraftStats",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerDraftStats",
    labelKey: "settings.composerDraftStats",
    descKeys: [
      "settings.composerDraftStatsDesc",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "draft",
      "stats",
      "character",
      "char count",
      "word count",
      "words",
      "length",
    ],
  },
  // ── general / permissions ──
  {
    id: "general.permissionPolicy",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-permissionPolicy",
    labelKey: "settings.permissionDeep",
    descKeys: [
      "settings.permissionDeepDesc",
      "settings.permissionCliMode",
      "settings.section.permissions",
      "policy.ask",
      "policy.accept_edits",
      "policy.allow_for_session",
      "policy.auto",
      "policy.dont_ask",
      "policy.always_approve",
    ],
    keywords: [
      "permission",
      "yolo",
      "always approve",
      "policy",
      "permission-mode",
      "acceptEdits",
      "bypassPermissions",
      "dontAsk",
    ],
  },
  {
    id: "general.cliPermissionMode",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-cliPermissionModeAdvanced",
    labelKey: "settings.permissionCliAdvanced",
    descKeys: [
      "settings.permissionCliAdvancedDesc",
      "settings.permissionCliAdvancedHint",
      "cliPermission.default",
      "cliPermission.acceptEdits",
      "cliPermission.auto",
      "cliPermission.dontAsk",
      "cliPermission.bypassPermissions",
      "cliPermission.plan",
    ],
    keywords: [
      "permission-mode",
      "cli",
      "default",
      "acceptEdits",
      "auto",
      "dontAsk",
      "bypassPermissions",
      "plan",
      "yolo",
    ],
  },
  {
    id: "general.sandbox",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-sandbox",
    labelKey: "settings.sandboxProfile",
    descKeys: [
      "settings.sandboxProfileDesc",
      "settings.sandbox.off",
      "settings.sandbox.off.help",
      "settings.sandbox.workspace",
      "settings.sandbox.workspace.help",
      "settings.sandbox.readOnly",
      "settings.sandbox.readOnly.help",
      "settings.sandbox.strict",
      "settings.sandbox.strict.help",
      "settings.sandbox.devbox",
      "settings.sandbox.devbox.help",
      "settings.sandbox.softFail.cliMissing",
      "settings.sandbox.softFail.cliUnsupported",
      "settings.sandbox.softFail.platform",
      "settings.sandbox.networkLinuxOnly",
      "settings.sandbox.recommendedNote",
      "settings.section.permissions",
    ],
    keywords: [
      "sandbox",
      "landlock",
      "seatbelt",
      "isolation",
      "devbox",
      "workspace sandbox",
      "read-only",
      "strict sandbox",
      "soft-fail",
      "GROK_SANDBOX",
      "--sandbox",
      "沙箱",
      "隔离",
      "沙箱設定",
      "沙箱配置",
    ],
  },
  {
    id: "general.permissionRules",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-permissionRules",
    labelKey: "settings.section.permissions",
    keywords: ["rules", "permission rules"],
  },
  {
    id: "general.permissionTimeout",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-permissionTimeout",
    labelKey: "settings.permissionTimeout",
    descKeys: [
      "settings.permissionTimeoutDesc",
      "settings.permissionTimeout.off",
      "settings.section.permissions",
    ],
    keywords: [
      "auto-deny",
      "timeout",
      "permission timeout",
      "auto deny",
      "自动拒绝",
      "超时",
    ],
  },
  {
    id: "general.askUserTimeout",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-askUserTimeout",
    labelKey: "settings.askUserTimeout",
    descKeys: [
      "settings.askUserTimeoutDesc",
      "settings.askUserTimeout.off",
      "settings.section.permissions",
      "askUser.title",
    ],
    keywords: [
      "ask user",
      "ask question",
      "questionnaire",
      "timeout",
      "auto-dismiss",
      "auto cancel",
      "ask_user_question",
      "提问超时",
      "问卷",
      "自动忽略",
      "超时",
    ],
  },
  // ── general / agent ──
  {
    id: "general.maxAgentTurns",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-maxAgentTurns",
    labelKey: "settings.maxAgentTurns",
    descKeys: ["settings.maxAgentTurnsDesc", "settings.section.agent"],
    keywords: ["max turns", "turns"],
  },
  {
    id: "general.backgroundWaitPolicy",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-backgroundWait",
    labelKey: "settings.backgroundWaitPolicy",
    descKeys: [
      "settings.backgroundWaitPolicyDesc",
      "settings.backgroundWait.wait",
      "settings.backgroundWait.noWait",
      "settings.backgroundWait.timeout",
      "settings.backgroundWaitTimeout",
      "settings.backgroundWaitTimeoutDesc",
      "settings.section.agent",
    ],
    keywords: [
      "background wait",
      "no-wait-for-background",
      "background-wait-timeout",
      "headless wait",
      "background tasks",
      "wait for background",
      "后台等待",
      "背景等待",
      "不等待后台",
    ],
  },
  {
    id: "general.preferredAgent",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-preferredAgent",
    labelKey: "settings.preferredAgent",
    descKeys: ["settings.preferredAgentDesc"],
    keywords: ["preferred agent", "agent definition"],
  },
  {
    id: "general.agentProfilePath",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-agentProfilePath",
    labelKey: "settings.agentProfilePath",
    descKeys: [
      "settings.agentProfilePathDesc",
      "settings.agentProfilePathBrowse",
      "settings.agentProfilePathClear",
    ],
    keywords: [
      "agent profile",
      "agent-profile",
      "profile path",
      "agent profile path",
      "profile 文件",
      "profile 路徑",
      "agent profile 路径",
    ],
  },
  {
    id: "general.configTomlView",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-configTomlView",
    labelKey: "settings.configTomlView",
    descKeys: [
      "settings.configTomlViewDesc",
      "settings.configTomlView.open",
      "settings.configTomlView.redactNote",
      "settings.configTomlView.sharedWarning",
    ],
    keywords: [
      "config.toml",
      "agent config",
      "view config",
      "config view",
      "redacted config",
      "agent-home config",
      "配置文件",
      "查看配置",
      "config 檢視",
    ],
  },
  {
    id: "general.agentsJson",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-agentsJson",
    labelKey: "settings.agentsJson",
    descKeys: [
      "settings.agentsJsonDesc",
      "settings.agentsJsonPlaceholder",
      "settings.agentsJsonInvalid",
      "settings.agentsJsonApply",
      "settings.agentsJsonClear",
    ],
    keywords: [
      "agents json",
      "--agents",
      "inline agents",
      "subagent definitions",
      "agents JSON",
      "内联 agents",
      "內聯 agents",
      "子代理 JSON",
    ],
  },
  {
    id: "general.experimentalMemory",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-experimentalMemory",
    labelKey: "settings.experimentalMemory",
    descKeys: ["settings.experimentalMemoryDesc"],
    keywords: ["memory"],
  },
  {
    id: "general.compactionMode",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-compactionMode",
    labelKey: "settings.compactionMode",
    descKeys: [
      "settings.compactionModeDesc",
      "settings.compactionMode.summary",
      "settings.compactionMode.transcript",
      "settings.compactionMode.segments",
      "settings.compactionMode.summary.help",
      "settings.compactionMode.transcript.help",
      "settings.compactionMode.segments.help",
    ],
    keywords: [
      "compaction",
      "compaction mode",
      "compact mode",
      "--compaction-mode",
      "GROK_COMPACTION_MODE",
      "summary",
      "transcript",
      "segments",
      "压缩模式",
      "壓縮模式",
    ],
  },
  {
    id: "general.compactionDetail",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-compactionDetail",
    labelKey: "settings.compactionDetail",
    descKeys: [
      "settings.compactionDetailDesc",
      "settings.compactionDetail.none",
      "settings.compactionDetail.minimal",
      "settings.compactionDetail.balanced",
      "settings.compactionDetail.verbose",
      "settings.compactionDetail.help",
    ],
    keywords: [
      "compaction detail",
      "segments detail",
      "--compaction-detail",
      "GROK_COMPACTION_DETAIL",
      "minimal",
      "balanced",
      "verbose",
      "分段细节",
      "分段細節",
    ],
  },
  {
    id: "general.twoPassCompaction",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-twoPassCompaction",
    labelKey: "settings.twoPassCompaction",
    descKeys: ["settings.twoPassCompactionDesc"],
    keywords: [
      "two pass compaction",
      "two-pass",
      "prefire",
      "two_pass_compaction_enabled",
      "GROK_TWO_PASS_COMPACTION",
      "hierarchical compact",
      "双遍压缩",
      "雙遍壓縮",
      "两遍压缩",
      "兩遍壓縮",
    ],
  },
  {
    id: "general.memoryBrowser",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-memoryBrowser",
    labelKey: "settings.memoryBrowser",
    descKeys: [
      "settings.memoryBrowserDesc",
      "settings.memoryBrowser.off",
      "settings.memoryBrowser.filterEmpty",
      "settings.memoryBrowser.filterEmptyHintKind",
      "settings.memoryBrowser.searchEmptyHint",
      "settings.memoryBrowser.searchEmptyHintKeyword",
      "settings.memoryBrowser.searchEmptyHintHybridUnavailable",
      "settings.memoryBrowser.emptyHint",
      "settings.clearWorkspaceMemory",
      "settings.memoryBrowser.searchMode.appKeyword",
      "settings.memoryBrowser.searchMode.hybridUnavailable",
      "settings.memoryBrowser.searchKind.hybridUnavailable",
      "settings.memoryBrowser.embedUnsetHint",
      "settings.memoryBrowser.hybridUnavailableHint",
    ],
    keywords: [
      "memory browser",
      "MEMORY.md",
      "workspace memory",
      "browse memory",
      "memory filter",
      "memory search",
      "hybrid search",
      "hybrid unavailable",
      "content search",
      "keyword only",
      "no embeddings",
      "reveal",
      "记忆",
      "記憶",
      "memory files",
      "记忆搜索",
      "記憶搜尋",
      "混合检索",
      "混合檢索",
      "embedding",
      "keyword search",
      "kind filter",
    ],
  },
  {
    id: "general.memoryEmbed",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-memoryEmbed",
    labelKey: "settings.memoryEmbed",
    descKeys: [
      "settings.memoryEmbedDesc",
      "settings.memoryEmbed.model",
      "settings.memoryEmbed.mmr",
      "settings.memoryEmbed.dream",
      "settings.memoryEmbed.embeddingEmpty",
      "settings.memoryEmbed.sharedWarning",
    ],
    keywords: [
      "memory embedding",
      "embedding model",
      "memory_embedding_model",
      "memory search",
      "mmr",
      "memory_mmr",
      "dream",
      "temporal decay",
      "vector search",
      "hybrid search",
      "memory.embed",
      "记忆 embedding",
      "記憶 embedding",
      "向量",
      "0.2.117",
    ],
  },
  {
    id: "general.codebaseIndexing",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-codebaseIndexing",
    labelKey: "settings.codebaseIndexing",
    descKeys: [
      "settings.codebaseIndexingDesc",
      "settings.codebaseIndexing.enable",
      "settings.codebaseIndexing.enableDesc",
      "settings.codebaseIndexing.noEmbeddings",
      "settings.codebaseIndexing.sharedWarning",
      "settings.codebaseIndexing.unsetDefaultHint",
    ],
    keywords: [
      "codebase indexing",
      "codebase_indexing",
      "code graph",
      "code-nav",
      "features.codebase_indexing",
      "[features] codebase_indexing",
      "index",
      "代码库索引",
      "程式碼庫索引",
      "代码图",
      "not embeddings",
      "0.2.117",
    ],
  },
  {
    id: "general.codebaseSearch",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-codebaseSearch",
    labelKey: "settings.codebaseSearch",
    descKeys: [
      "settings.codebaseSearchDesc",
      "settings.codebaseSearch.noEmbeddings",
      "settings.codebaseSearch.idleHint",
      "settings.codebaseSearch.mode.all",
      "settings.codebaseSearch.mode.name",
      "settings.codebaseSearch.mode.content",
    ],
    keywords: [
      "codebase search",
      "project search",
      "file search",
      "content search",
      "rg",
      "ripgrep",
      "keyword search",
      "find in files",
      "代码库搜索",
      "專案搜尋",
      "文件搜索",
      "內容搜尋",
      "not embeddings",
    ],
  },
  {
    id: "general.subagents",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-subagents",
    labelKey: "settings.subagentsEnabled",
    descKeys: ["settings.subagentsEnabledDesc"],
    keywords: ["subagents", "sub-agent"],
  },
  {
    id: "general.subagentWorktreeSnapshot",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-subagentWtSnap",
    labelKey: "settings.subagentWorktreeSnapshot",
    descKeys: [
      "settings.subagentWorktreeSnapshotDesc",
      "tasks.subagentWtSnapNote",
    ],
    keywords: [
      "subagent worktree snapshot",
      "subagent_worktree_snapshot_enabled",
      "GROK_SUBAGENT_WORKTREE_SNAPSHOT",
      "worktree snapshot",
      "subagent snapshot",
      "子代理 worktree 快照",
      "子代理工作樹快照",
      "快照",
    ],
  },
  {
    id: "general.autoWake",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-autoWake",
    labelKey: "settings.autoWake",
    descKeys: ["settings.autoWakeDesc"],
    keywords: [
      "auto wake",
      "auto-wake",
      "auto_wake_enabled",
      "background task wake",
      "synthetic turn",
      "task completed",
      "monitor wake",
      "自动唤醒",
      "自動喚醒",
      "后台任务",
      "背景任務",
    ],
  },
  {
    id: "general.configTomlEdit",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-configTomlEdit",
    labelKey: "settings.configTomlEdit",
    descKeys: [
      "settings.configTomlEditDesc",
      "settings.configTomlEdit.sharedWarning",
      "settings.configTomlEdit.redactNote",
    ],
    keywords: [
      "config.toml",
      "agent-home",
      "config edit",
      "section edit",
      "permission_mode",
      "yolo",
      "subagents",
      "memory",
      "workflows",
      "workflows_enabled",
      "auto_wake",
      "auto_wake_enabled",
      "two_pass_compaction",
      "lsp_tools",
      "codebase_indexing",
      "remote_fetch",
      "features",
      "GROK_HOME",
      "配置编辑",
      "配置編輯",
      "agent-home 配置",
      "工作流",
      "自动唤醒",
      "自動喚醒",
      "两遍压缩",
      "兩遍壓縮",
    ],
  },
  {
    id: "general.plan",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-planEnabled",
    labelKey: "settings.planEnabled",
    descKeys: ["settings.planEnabledDesc"],
    keywords: ["plan mode"],
  },
  {
    id: "general.todoGate",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-todoGate",
    labelKey: "settings.todoGate",
    descKeys: [
      "settings.todoGateDesc",
      "settings.todoGate.softRespawnNote",
      "settings.todoGate.activity.na",
      "settings.todoGateMaxFires",
      "settings.todoGateMaxFiresDesc",
      "settings.todoGateMaxFires.effective",
      "settings.todoGateMaxFires.independent",
      "settings.todoGateMaxFires.shared",
      "settings.todoGateMaxFires.inactive",
    ],
    keywords: [
      "todo gate",
      "todogate",
      "--todo-gate",
      "todo_gate_enabled",
      "todo_gate_max_fires_per_prompt",
      "max fires",
      "pending todos",
      "turn-end",
      "TodoGate",
      "soft-respawn",
      "gate activity",
      "待办门控",
      "待辦門控",
      "todo 门控",
      "最大触发",
      "最大觸發",
    ],
  },
  {
    id: "general.disableWebSearch",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-disableWebSearch",
    labelKey: "settings.disableWebSearch",
    descKeys: ["settings.disableWebSearchDesc"],
    keywords: ["web search"],
  },
  {
    id: "general.noAskUser",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-noAskUser",
    labelKey: "settings.noAskUser",
    descKeys: ["settings.noAskUserDesc"],
    keywords: [
      "no ask user",
      "no-ask-user",
      "ask_user_question",
      "ask user",
      "questionnaire",
      "0.2.117",
      "不问用户",
      "不问用户问题",
      "禁用提问",
    ],
  },
  {
    id: "general.allowedTools",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-allowedTools",
    labelKey: "settings.allowedTools",
    descKeys: [
      "settings.allowedToolsDesc",
      "settings.allowedTools.bothSet",
    ],
    keywords: [
      "allowed tools",
      "allowlist",
      "tools allow",
      "--tools",
      "web_search",
      "run_terminal_command",
      "tool allow",
    ],
  },
  {
    id: "general.disallowedTools",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-disallowedTools",
    labelKey: "settings.disallowedTools",
    descKeys: [
      "settings.disallowedToolsDesc",
      "settings.disallowedTools.webCovered",
      "settings.allowedTools.bothSet",
    ],
    keywords: [
      "disallowed tools",
      "deny tools",
      "web_search",
      "web_fetch",
      "run_terminal_command",
      "tool deny",
    ],
  },
  {
    id: "general.useLeader",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-useLeader",
    labelKey: "settings.useLeader",
    descKeys: ["settings.useLeaderDesc"],
    keywords: ["leader"],
  },
  // ── general / app ──
  {
    id: "general.language",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-language",
    labelKey: "settings.language",
    descKeys: ["settings.languageDesc", "settings.section.general"],
    keywords: [
      "language",
      "locale",
      "中文",
      "english",
      "system",
      "跟随系统",
      "跟隨系統",
    ],
  },
  {
    id: "general.sessionDataMode",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-sessionDataMode",
    labelKey: "settings.sessionDataMode",
    descKeys: [
      "settings.sessionDataModeDesc",
      "settings.modeIndependent",
      "settings.modeShared",
      "settings.cliSessions",
    ],
    keywords: ["session data", "shared", "independent", "cli sessions"],
  },
  {
    id: "general.cliSessions",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-cliSessions",
    labelKey: "settings.cliSessions",
    descKeys: [
      "settings.cliSessionsDesc",
      "settings.cliSessionsIndependentNote",
      "settings.cliSessionsImportOpen",
      "settings.cliSessionsDelete",
      "settings.cliSessionsDeleteUnlinked",
      "settings.cliSessionsFilterPlaceholder",
      "settings.cliSessionsSearchViaCli",
    ],
    keywords: [
      "cli sessions",
      "import session",
      "agent session id",
      "resume",
      "delete session",
      "search sessions",
      "first prompt",
      "CLI 会话",
      "导入会话",
      "删除会话",
      "搜索会话",
      "首条提示",
    ],
  },
  {
    id: "general.voiceHotkeyEnabled",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceHotkeyEnabled",
    labelKey: "settings.voiceHotkeyEnabled",
    descKeys: ["settings.voiceHotkeyEnabledDesc", "settings.section.voice"],
    keywords: [
      "voice",
      "hotkey",
      "shortcut",
      "live voice",
      "keyboard",
      "语音",
      "快捷键",
      "实时语音",
    ],
  },
  {
    id: "general.voiceId",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceId",
    labelKey: "settings.voiceId",
    descKeys: ["settings.voiceIdDesc", "settings.section.voice"],
    keywords: ["voice", "speaker", "tts", "语音", "音色"],
  },
  {
    id: "general.voiceDictationAutoSend",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceDictationAutoSend",
    labelKey: "settings.voiceDictationAutoSend",
    descKeys: ["settings.voiceDictationAutoSendDesc"],
    keywords: ["dictation", "auto send", "听写", "语音输入"],
  },
  {
    id: "general.voiceKeepAgentsOnEnd",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceKeepAgentsOnEnd",
    labelKey: "settings.voiceKeepAgentsOnEnd",
    descKeys: ["settings.voiceKeepAgentsOnEndDesc"],
    keywords: ["voice", "keep agents", "语音", "保留"],
  },
  {
    id: "general.keychain",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-keychain",
    labelKey: "settings.storeApiKeysInKeychain",
    descKeys: ["settings.storeApiKeysInKeychainDesc"],
    keywords: ["keychain", "api key", "secrets"],
  },
  {
    id: "general.clearMemory",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-clearMemory",
    labelKey: "settings.clearWorkspaceMemory",
    descKeys: ["settings.clearWorkspaceMemoryDesc"],
    keywords: ["clear memory", "workspace memory"],
  },
  {
    id: "general.reopenLastSession",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-reopenLastSession",
    labelKey: "settings.reopenLastSession",
    descKeys: ["settings.reopenLastSessionDesc"],
    keywords: ["reopen", "restore session"],
  },
  {
    id: "general.closeToTray",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-closeToTray",
    labelKey: "settings.closeToTray",
    descKeys: ["settings.closeToTrayDesc"],
    keywords: ["tray", "close", "minimize", "托盘", "系統匣", "关闭"],
  },
  {
    id: "general.keepTrayForSchedules",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-keepTrayForSchedules",
    labelKey: "settings.keepTrayForSchedules",
    descKeys: ["settings.keepTrayForSchedulesDesc"],
    keywords: [
      "tray",
      "schedules",
      "automations",
      "background",
      "keep",
      "scheduled",
      "托盘",
      "已安排",
      "调度",
      "系统匣",
      "排程",
    ],
  },
  {
    id: "general.trayBusyBadge",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-trayBusyBadge",
    labelKey: "settings.trayBusyBadge",
    descKeys: [
      "settings.trayBusyBadgeDesc",
      "settings.trayBusyBadge.status.off",
      "settings.trayBusyBadge.status.idle",
      "settings.trayBusyBadge.status.busy",
      "settings.trayBusyBadge.status.capped",
    ],
    keywords: [
      "badge",
      "dock",
      "tray",
      "busy",
      "count",
      "角标",
      "徽章",
      "托盘",
      "忙碌",
      "系統匣",
      "notify",
      "notification",
    ],
  },
  {
    id: "general.notifyHonesty",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyHonesty",
    labelKey: "settings.notify.honesty.title",
    descKeys: [
      "settings.notify.honesty.desc",
      "settings.notify.honesty.ok",
      "settings.notify.honesty.osDenied",
      "settings.notify.honesty.osDefault",
      "settings.notify.honesty.osUnsupported",
      "settings.notify.honesty.prefsOff",
      "settings.notify.honesty.quietHours",
    ],
    keywords: [
      "notification",
      "desktop",
      "permission",
      "os",
      "quiet hours",
      "dnd",
      "notify",
      "桌面通知",
      "系统权限",
      "免打扰",
      "通知權限",
    ],
  },
  {
    id: "general.launchAtLogin",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-launchAtLogin",
    labelKey: "settings.launchAtLogin",
    descKeys: ["settings.launchAtLoginDesc"],
    keywords: [
      "launch",
      "login",
      "startup",
      "autostart",
      "boot",
      "automation",
      "scheduled",
      "schedule",
      "daemon",
      "background",
      "开机",
      "登录",
      "啟動",
      "登入",
      "自动化",
      "已安排",
      "排程",
      "后台",
      "背景",
    ],
  },
  {
    id: "general.windowAlwaysOnTop",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-windowAlwaysOnTop",
    labelKey: "settings.windowAlwaysOnTop",
    descKeys: ["settings.windowAlwaysOnTopDesc"],
    keywords: [
      "always on top",
      "pin",
      "float",
      "stay on top",
      "置顶",
      "置頂",
      "窗口",
      "視窗",
    ],
  },
  {
    id: "general.notifyOnTurnDone",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyOnTurnDone",
    labelKey: "settings.notifyOnTurnDone",
    descKeys: ["settings.notifyOnTurnDoneDesc"],
    keywords: [
      "notification",
      "desktop",
      "alert",
      "turn done",
      "notify",
      "桌面通知",
      "完成通知",
    ],
  },
  {
    id: "general.notifyOnPermission",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyOnPermission",
    labelKey: "settings.notifyOnPermission",
    descKeys: ["settings.notifyOnPermissionDesc"],
    keywords: [
      "notification",
      "desktop",
      "alert",
      "permission",
      "notify",
      "桌面通知",
      "授权通知",
    ],
  },
  {
    id: "general.notifySound",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifySound",
    labelKey: "settings.notifySound",
    descKeys: ["settings.notifySoundDesc"],
    keywords: [
      "notification",
      "sound",
      "beep",
      "audio",
      "alert",
      "notify",
      "通知声音",
      "提示音",
    ],
  },
  {
    id: "general.notifyQuietHours",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyQuietHours",
    labelKey: "settings.notifyQuietHours",
    descKeys: [
      "settings.notifyQuietHoursDesc",
      "settings.notifyQuietHoursStart",
      "settings.notifyQuietHoursEnd",
      "settings.notifyQuietHours.activeNow",
    ],
    keywords: [
      "quiet hours",
      "do not disturb",
      "dnd",
      "notification",
      "desktop",
      "mute",
      "night",
      "免打扰",
      "勿扰",
      "静音时段",
      "桌面通知",
    ],
  },
  {
    id: "general.stopAllSkipConfirm",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-stopAllSkipConfirm",
    labelKey: "settings.stopAllSkipConfirm",
    descKeys: ["settings.stopAllSkipConfirmDesc"],
    keywords: [
      "stop all",
      "skip confirm",
      "busy sessions",
      "tasks",
      "dashboard",
      "no confirm",
      "全部停止",
      "跳过确认",
      "忙碌会话",
    ],
  },
  {
    id: "general.alwaysQuitWithoutAsking",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-alwaysQuitWithoutAsking",
    labelKey: "settings.alwaysQuitWithoutAsking",
    descKeys: ["settings.alwaysQuitWithoutAskingDesc"],
    keywords: [
      "quit",
      "exit",
      "close",
      "busy",
      "confirm",
      "always quit",
      "without asking",
      "退出",
      "结束",
      "忙碌",
      "确认",
      "不再询问",
    ],
  },
  {
    id: "general.openTarget",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-openTarget",
    labelKey: "settings.openTarget",
    descKeys: ["settings.openTargetDesc", "settings.openFinder"],
    keywords: ["open in", "finder", "editor"],
  },
  // ── appearance · theme ──
  {
    id: "appearance.theme",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-theme",
    labelKey: "settings.theme",
    descKeys: [
      "settings.themeDesc",
      "settings.themeSystem",
      "settings.themeLight",
      "settings.themeDark",
    ],
    keywords: ["theme", "dark", "light", "system", "auto", "跟随系统"],
  },
  {
    id: "appearance.themeSchedule",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-themeSchedule",
    labelKey: "settings.themeSchedule",
    descKeys: [
      "settings.themeScheduleDesc",
      "settings.themeScheduleLightFrom",
      "settings.themeScheduleDarkFrom",
      "settings.themeSchedule.nextSwitch",
      "settings.themeSchedule.nextSwitchTomorrow",
      "settings.themeSchedule.invalidEqual",
      "settings.themeSchedule.invalidTimes",
      "settings.themeSchedule.inactivePref",
    ],
    keywords: [
      "schedule",
      "timed",
      "auto theme",
      "light from",
      "dark from",
      "next switch",
      "clock",
      "定时",
      "定時",
      "按时切换",
      "按時切換",
      "浅色开始",
      "深色开始",
      "下次切换",
      "下次切換",
    ],
  },
  {
    id: "appearance.skin",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-skin",
    labelKey: "settings.skin",
    descKeys: ["settings.skinDesc"],
    keywords: ["skin", "color pack", "accent"],
  },
  {
    id: "appearance.wallpaper",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-wallpaper",
    labelKey: "settings.wallpaper",
    descKeys: [
      "settings.wallpaperDesc",
      "settings.wallpaperScrim",
      "settings.wallpaperScrimDesc",
      "settings.wallpaperFromX",
      "settings.wallpaperImagine",
    ],
    keywords: [
      "wallpaper",
      "background",
      "scrim",
      "x",
      "twitter",
      "imagine",
      "背景",
      "壁纸",
    ],
  },
  // ── appearance · interface (chat chrome) ──
  {
    id: "appearance.zenMode",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-zenMode",
    labelKey: "settings.zenMode",
    descKeys: ["settings.zenModeDesc"],
    keywords: [
      "zen",
      "focus",
      "distraction free",
      "distraction-free",
      "hide sidebar",
      "hide panes",
      "maximize chat",
      "fullscreen chat",
      "禅",
      "禪",
      "专注",
      "專注",
      "沉浸",
      "隐藏侧栏",
      "隱藏側欄",
      "最大化",
    ],
  },
  {
    id: "appearance.thinkingExpand",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-thinkingExpand",
    labelKey: "settings.thinkingExpand",
    descKeys: [
      "settings.thinkingExpandDesc",
      "settings.thinkingExpand.autoCollapse",
      "settings.thinkingExpand.keepOpen",
    ],
    keywords: [
      "thinking",
      "reasoning",
      "collapse",
      "expand",
      "thought",
      "思考",
      "推理",
      "折叠",
      "展開",
      "展开",
    ],
  },
  {
    id: "appearance.toolStepsAutoCollapse",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-toolStepsAutoCollapse",
    labelKey: "settings.toolStepsAutoCollapse",
    descKeys: ["settings.toolStepsAutoCollapseDesc"],
    keywords: [
      "tool",
      "tools",
      "tool steps",
      "collapse",
      "auto collapse",
      "timeline",
      "activity",
      "工具",
      "工具步骤",
      "工具步驟",
      "折叠",
      "摺疊",
      "时间线",
      "時間線",
    ],
  },
  {
    id: "appearance.transcriptFilter",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-transcriptFilter",
    labelKey: "settings.transcriptFilter",
    descKeys: [
      "settings.transcriptFilterDesc",
      "settings.transcriptFilter.all",
      "settings.transcriptFilter.conversation",
    ],
    keywords: [
      "transcript",
      "filter",
      "tool steps",
      "hide tools",
      "conversation only",
      "activity",
      "timeline",
      "clean",
      "hide tool steps",
      "对话过滤",
      "對話過濾",
      "隐藏工具",
      "隱藏工具",
      "仅对话",
      "僅對話",
      "工具步骤",
      "工具步驟",
      "transcript filter",
    ],
  },
  {
    id: "appearance.chatFontScale",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-chatFontScale",
    labelKey: "settings.chatFontScale",
    descKeys: [
      "settings.chatFontScaleDesc",
      "settings.chatFontScale.sm",
      "settings.chatFontScale.md",
      "settings.chatFontScale.lg",
    ],
    keywords: ["font", "size", "text size", "字号", "字號", "字体", "字體"],
  },
  {
    id: "appearance.codeFontScale",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-codeFontScale",
    labelKey: "settings.codeFontScale",
    descKeys: [
      "settings.codeFontScaleDesc",
      "settings.codeFontScale.sm",
      "settings.codeFontScale.md",
      "settings.codeFontScale.lg",
    ],
    keywords: [
      "code font",
      "code size",
      "monospace",
      "pre",
      "code block",
      "代码字号",
      "程式碼字號",
      "代码字体",
      "程式碼字體",
    ],
  },
  {
    id: "appearance.chatDensity",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-chatDensity",
    labelKey: "settings.chatDensity",
    descKeys: [
      "settings.chatDensityDesc",
      "settings.chatDensity.comfortable",
      "settings.chatDensity.compact",
    ],
    keywords: [
      "density",
      "compact",
      "comfortable",
      "spacing",
      "padding",
      "dense",
      "密度",
      "紧凑",
      "緊湊",
      "舒适",
      "舒適",
      "间距",
      "間距",
    ],
  },
  {
    id: "appearance.chatWidth",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-chatWidth",
    labelKey: "settings.chatWidth",
    descKeys: [
      "settings.chatWidthDesc",
      "settings.chatWidth.narrow",
      "settings.chatWidth.medium",
      "settings.chatWidth.wide",
      "settings.chatWidth.full",
    ],
    keywords: [
      "width",
      "reading width",
      "transcript",
      "narrow",
      "medium",
      "wide",
      "full",
      "max-width",
      "column",
      "宽度",
      "寬度",
      "阅读",
      "閱讀",
      "窄",
      "中",
      "宽",
      "寬",
      "全宽",
      "全寬",
    ],
  },
  {
    id: "appearance.sidebarDensity",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-sidebarDensity",
    labelKey: "settings.sidebarDensity",
    descKeys: [
      "settings.sidebarDensityDesc",
      "settings.sidebarDensity.comfortable",
      "settings.sidebarDensity.compact",
    ],
    keywords: [
      "sidebar",
      "session list",
      "density",
      "compact",
      "comfortable",
      "spacing",
      "sessions",
      "侧栏",
      "側欄",
      "会话",
      "會話",
      "列表",
      "密度",
      "紧凑",
      "緊湊",
      "舒适",
      "舒適",
    ],
  },
  {
    id: "appearance.codeWrapDefault",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-codeWrapDefault",
    labelKey: "settings.codeWrapDefault",
    descKeys: ["settings.codeWrapDefaultDesc"],
    keywords: [
      "code wrap",
      "line wrap",
      "word wrap",
      "soft wrap",
      "代码换行",
      "自動換行",
      "自动换行",
    ],
  },
  {
    id: "appearance.codeLineNumbers",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-codeLineNumbers",
    labelKey: "settings.codeLineNumbers",
    descKeys: ["settings.codeLineNumbersDesc"],
    keywords: [
      "line numbers",
      "code lines",
      "gutter",
      "行号",
      "行號",
      "代码行号",
      "程式碼行號",
    ],
  },
  {
    id: "appearance.backBottomAlways",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-backBottomAlways",
    labelKey: "settings.backBottomAlways",
    descKeys: ["settings.backBottomAlwaysDesc"],
    keywords: [
      "back to bottom",
      "scroll to bottom",
      "always show",
      "scroll button",
      "回到底部",
      "回到最新",
      "始终显示",
      "始終顯示",
      "滚动",
      "滾動",
    ],
  },
  {
    id: "appearance.sessionSearchRank",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-sessionSearchRank",
    labelKey: "settings.sessionSearchRank",
    descKeys: [
      "settings.sessionSearchRankDesc",
      "settings.sessionSearchRank.keyword",
      "settings.sessionSearchRank.hybrid",
    ],
    keywords: [
      "session search",
      "hybrid search",
      "semantic search",
      "token overlap",
      "keyword ranking",
      "command palette",
      "include archived",
      "title content filter",
      "clear filters",
      "empty state",
      "会话搜索",
      "混合搜索",
      "语义",
      "語意",
      "关键词",
      "關鍵字",
      "词元",
      "已归档",
      "已封存",
      "筛选",
      "篩選",
      "詞元",
      "命令面板",
    ],
  },
  {
    id: "appearance.confirmExternalLinks",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-confirmExternalLinks",
    labelKey: "settings.confirmExternalLinks",
    descKeys: ["settings.confirmExternalLinksDesc"],
    keywords: [
      "external link",
      "confirm link",
      "open link",
      "http",
      "https",
      "safety",
      "外链",
      "确认",
      "確認",
      "打开链接",
      "開啟連結",
    ],
  },
  {
    id: "appearance.messageActions",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-messageActions",
    labelKey: "settings.messageActions",
    descKeys: [
      "settings.messageActionsDesc",
      "settings.messageActions.hover",
      "settings.messageActions.always",
    ],
    keywords: [
      "actions",
      "hover",
      "copy buttons",
      "message actions",
      "always show",
      "操作",
      "按钮",
      "按鈕",
      "复制",
      "複製",
    ],
  },
  {
    id: "appearance.messageTimestamps",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-messageTimestamps",
    labelKey: "settings.messageTimestamps",
    descKeys: ["settings.messageTimestampsDesc"],
    keywords: [
      "timestamp",
      "timestamps",
      "message time",
      "time label",
      "时间戳",
      "时间",
      "時間戳",
    ],
  },
  {
    id: "appearance.showUsageEstimates",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-showUsageEstimates",
    labelKey: "settings.showUsageEstimates",
    descKeys: ["settings.showUsageEstimatesDesc"],
    keywords: [
      "usage",
      "cost",
      "estimate",
      "tokens",
      "usd",
      "price",
      "billing",
      "context chip",
      "用量",
      "费用",
      "費用",
      "估算",
      "成本",
      "token",
    ],
  },
  {
    id: "appearance.goalOrchUi",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-goalOrchUi",
    labelKey: "settings.goalOrchUi",
    descKeys: ["settings.goalOrchUiDesc"],
    keywords: [
      "goal",
      "orchestration",
      "classifier",
      "planner",
      "strategist",
      "verifier",
      "goal_updated",
      "reliability",
      "目标",
      "目标编排",
      "目标編排",
      "可靠性",
    ],
  },
  {
    id: "appearance.exportLogo",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-exportLogo",
    labelKey: "settings.exportLogo",
    descKeys: ["settings.exportLogoDesc"],
    keywords: [
      "export logo",
      "share card",
      "export image",
      "branding",
      "watermark",
      "custom logo",
      "导出图片",
      "导出 logo",
      "分享卡片",
      "品牌",
      "匯出圖片",
      "自訂 logo",
    ],
  },
  {
    id: "appearance.showReplyLength",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-showReplyLength",
    labelKey: "settings.showReplyLength",
    descKeys: ["settings.showReplyLengthDesc"],
    keywords: [
      "word count",
      "character count",
      "reply length",
      "message length",
      "chars",
      "words",
      "字数",
      "字數",
      "词数",
      "詞數",
      "回复长度",
      "回覆長度",
    ],
  },
  {
    id: "appearance.messageTimeFormat",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-messageTimeFormat",
    labelKey: "settings.messageTimeFormat",
    descKeys: [
      "settings.messageTimeFormatDesc",
      "settings.messageTimeFormat.absolute",
      "settings.messageTimeFormat.relative",
    ],
    keywords: [
      "timestamp",
      "relative",
      "relative time",
      "absolute",
      "time format",
      "ago",
      "时间戳",
      "相对时间",
      "相對時間",
      "相對",
      "相对",
    ],
  },
  {
    id: "appearance.sidebarShowRelativeTime",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-sidebarShowRelativeTime",
    labelKey: "settings.sidebarShowRelativeTime",
    descKeys: ["settings.sidebarShowRelativeTimeDesc"],
    keywords: [
      "sidebar",
      "session list",
      "relative time",
      "updated",
      "ago",
      "last active",
      "侧栏",
      "側欄",
      "会话",
      "會話",
      "相对时间",
      "相對時間",
      "更新时间",
      "更新時間",
    ],
  },
  {
    id: "appearance.sessionMuteSummary",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-sessionMuteSummary",
    labelKey: "settings.sessionMuteSummary",
    descKeys: [
      "settings.sessionMuteSummaryDesc",
      "settings.sessionMuteCount",
      "settings.sessionMuteCountZero",
      "settings.sessionMuteClear",
    ],
    keywords: [
      "mute",
      "muted",
      "notifications",
      "desktop notify",
      "unread",
      "session mute",
      "unmute",
      "静音",
      "靜音",
      "通知",
      "未读",
      "未讀",
      "会话",
      "會話",
    ],
  },
  {
    id: "appearance.sessionUnreadSummary",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-sessionUnreadSummary",
    labelKey: "settings.sessionUnreadSummary",
    descKeys: [
      "settings.sessionUnreadSummaryDesc",
      "settings.sessionUnreadCount",
      "settings.sessionUnreadCountZero",
      "settings.sessionUnreadClear",
    ],
    keywords: [
      "unread",
      "read",
      "marker",
      "dot",
      "background turn",
      "clear unread",
      "未读",
      "未讀",
      "圆点",
      "圓點",
      "已读",
      "已讀",
      "会话",
      "會話",
    ],
  },
  // ── account ──
  {
    id: "account.official",
    section: "account",
    tab: "official",
    anchorId: "settings-anchor-account-official",
    labelKey: "settings.tabOfficial",
    descKeys: [
      "settings.tabOfficialHint",
      "account.signedIn",
      "account.loginOauth",
      "account.loginDevice",
      "account.logout",
      "account.subscription",
      "account.quota",
      "account.profiles",
      "account.manageAccounts",
      "account.addAccount",
      "account.importChat",
    ],
    keywords: ["login", "oauth", "supergrok", "quota", "account"],
  },
  {
    id: "account.providers",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-account-providers",
    labelKey: "settings.tabProviders",
    descKeys: ["settings.tabProvidersHint"],
    keywords: [
      "provider",
      "relay",
      "custom api",
      "base url",
      "soft respawn",
      "live apply",
      "中转",
      "中轉",
      "提供商",
      "供應商",
    ],
  },
  {
    id: "account.officialApiKey",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-official-key",
    labelKey: "prov.officialApiKey",
    descKeys: ["prov.officialVoiceHint", "prov.officialDesc"],
    keywords: [
      "api key",
      "xai",
      "official key",
      "voice",
      "speech",
      "stt",
      "dictation",
      "语音",
      "語音",
      "听写",
    ],
  },
  {
    id: "account.extras",
    section: "account",
    tab: "extras",
    anchorId: "settings-anchor-account-extras",
    labelKey: "settings.tabExtras",
    descKeys: ["settings.tabExtrasHint"],
    keywords: [
      "extras",
      "拓展",
      "official tools",
      "inject",
      "official-aux",
      "官方工具",
    ],
  },
  {
    id: "account.officialAuxInject",
    section: "account",
    tab: "extras",
    anchorId: "settings-anchor-official-aux-inject",
    labelKey: "prov.officialAuxInject",
    descKeys: [
      "prov.officialAuxInjectDesc",
      "prov.officialAuxInjectDisabled",
      "prov.officialAuxWithUserMcp",
      "prov.officialAuxWithUserMcpDesc",
    ],
    keywords: [
      "official aux",
      "inject tools",
      "x_keyword_search",
      "web_search",
      "vision",
      "official-aux",
      "官方工具",
      "注入",
      "x搜索",
      "imagine",
      "image_gen",
      "画图",
      "custom only",
      "第三方",
      "MCP",
      "拓展",
    ],
  },
  // ── archived ──
  {
    id: "archived.list",
    section: "archived",
    anchorId: "settings-anchor-archived",
    labelKey: "settings.nav.archived",
    descKeys: [
      "settings.archived.desc",
      "settings.archived.empty",
      "settings.archived.restore",
      "settings.archived.delete",
      "settings.archived.selectAll",
    ],
    keywords: ["archive", "archived chats"],
  },
  {
    id: "archived.archiveOlder",
    section: "archived",
    anchorId: "settings-anchor-archive-older",
    labelKey: "settings.archived.archiveOlder",
    descKeys: [
      "settings.archived.archiveOlderDesc",
      "settings.archived.archiveOlderMatchHint",
      "settings.archived.archiveOlderNoneHint",
    ],
    keywords: [
      "archive older",
      "bulk archive",
      "archive by age",
      "preview count",
      "old chats",
      "7 days",
      "30 days",
      "90 days",
      "归档超过",
      "按时间归档",
      "封存超過",
    ],
  },
  // ── extensions ──
  {
    id: "ext.plugins",
    section: "extensions",
    tab: "plugins",
    anchorId: "settings-anchor-ext-plugins",
    labelKey: "ext.plugins.title",
    descKeys: ["ext.lead", "ext.plugins.installLabel"],
    keywords: ["plugin", "plugins", "extensions"],
  },
  {
    id: "ext.skills",
    section: "extensions",
    tab: "skills",
    anchorId: "settings-anchor-ext-skills",
    labelKey: "ext.skills.title",
    descKeys: ["ext.skills.edit", "ext.skills.editDisabledNote"],
    keywords: [
      "skill",
      "skills",
      "slash",
      "SKILL.md",
      "edit skill",
      "技能",
      "编辑技能",
    ],
  },
  {
    id: "ext.mcp",
    section: "extensions",
    tab: "mcp",
    anchorId: "settings-anchor-ext-mcp",
    labelKey: "ext.mcp.title",
    descKeys: [
      "ext.mcp.doctor",
      "ext.mcp.add",
      "mcpModal.oauth.authorize",
      "ext.mcp.auth.howToRefresh",
    ],
    keywords: [
      "mcp",
      "model context protocol",
      "server",
      "oauth",
      "authorize",
      "auth",
      "token",
      "credentials",
      "mcp doctor",
      "授权",
      "認證",
      "oauth 授权",
    ],
  },
  {
    id: "ext.agents",
    section: "extensions",
    tab: "agents",
    anchorId: "settings-anchor-ext-agents",
    labelKey: "ext.agents.title",
    descKeys: ["ext.agents.desc", "ext.agents.new"],
    keywords: [
      "agents",
      "agent definition",
      "persona",
      "scaffold",
      "new agent",
      "代理",
      "新建代理",
    ],
  },
  {
    id: "ext.hooks",
    section: "extensions",
    tab: "hooks",
    anchorId: "settings-anchor-ext-hooks",
    labelKey: "ext.hooks.title",
    keywords: ["hooks", "hook"],
  },
  {
    id: "ext.market",
    section: "extensions",
    tab: "market",
    anchorId: "settings-anchor-ext-market",
    labelKey: "ext.market.title",
    keywords: ["marketplace", "market", "install plugin"],
  },
  // ── runtime ──
  {
    id: "runtime.privacy",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy",
    labelKey: "settings.privacy",
    descKeys: [
      "settings.privacyDesc",
      "settings.privacy.telemetry",
      "settings.privacy.telemetryDesc",
      "settings.privacy.traceUpload",
      "settings.privacy.traceUploadDesc",
      "settings.privacy.mixpanel",
      "settings.privacy.disableCodebaseUpload",
      "settings.privacy.disableCodebaseUploadDesc",
      "settings.privacy.disableWorkspaceTeleport",
      "settings.privacy.codingData",
      "settings.privacy.codingDataDesc",
      "settings.privacy.sharedWarning",
      "settings.privacy.unsetNotOff",
      "settings.privacy.probe.okAllUnset",
      "settings.privacy.apply.softRespawn",
    ],
    keywords: [
      "privacy",
      "privacy center",
      "telemetry",
      "trace upload",
      "codebase upload",
      "disable_codebase_upload",
      "disable_workspace_teleport",
      "trace_upload",
      "mixpanel",
      "mixpanel_enabled",
      "GROK_TELEMETRY",
      "/privacy",
      "coding data",
      "training",
      "retention",
      "unset",
      "probe",
      "隐私",
      "遙測",
      "遥测",
      "隐私中心",
      "隱私",
      "未设置",
      "未設定",
    ],
  },
  {
    id: "runtime.privacy.telemetry",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-telemetry",
    labelKey: "settings.privacy.telemetry",
    descKeys: [
      "settings.privacy.telemetryDesc",
      "settings.privacy.default.telemetry",
      "settings.privacy.unsetNotOff",
    ],
    keywords: [
      "telemetry",
      "features telemetry",
      "product analytics",
      "GROK_TELEMETRY_ENABLED",
      "unset",
    ],
  },
  {
    id: "runtime.privacy.traceUpload",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-traceUpload",
    labelKey: "settings.privacy.traceUpload",
    descKeys: [
      "settings.privacy.traceUploadDesc",
      "settings.privacy.default.traceUpload",
    ],
    keywords: [
      "trace_upload",
      "session trace",
      "trace upload",
      "GROK_TELEMETRY_TRACE_UPLOAD",
    ],
  },
  {
    id: "runtime.privacy.mixpanel",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-mixpanel",
    labelKey: "settings.privacy.mixpanel",
    descKeys: [
      "settings.privacy.mixpanelDesc",
      "settings.privacy.default.mixpanel",
    ],
    keywords: [
      "mixpanel",
      "mixpanel_enabled",
      "GROK_TELEMETRY_MIXPANEL_ENABLED",
      "product analytics",
    ],
  },
  {
    id: "runtime.privacy.codebaseUpload",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-codebaseUpload",
    labelKey: "settings.privacy.disableCodebaseUpload",
    descKeys: [
      "settings.privacy.disableCodebaseUploadDesc",
      "settings.privacy.default.disableCodebaseUpload",
    ],
    keywords: [
      "disable_codebase_upload",
      "codebase upload",
      "upload codebase",
      "index upload",
      "harness",
    ],
  },
  {
    id: "runtime.privacy.workspaceTeleport",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-workspaceTeleport",
    labelKey: "settings.privacy.disableWorkspaceTeleport",
    descKeys: [
      "settings.privacy.disableWorkspaceTeleportDesc",
      "settings.privacy.default.disableWorkspaceTeleport",
    ],
    keywords: [
      "disable_workspace_teleport",
      "workspace teleport",
      "teleport",
      "harness",
    ],
  },
  {
    id: "runtime.privacy.codingData",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-codingData",
    labelKey: "settings.privacy.codingData",
    descKeys: [
      "settings.privacy.codingDataDesc",
      "settings.privacy.codingDataHint",
    ],
    keywords: [
      "/privacy",
      "coding data",
      "training",
      "retention",
      "ZDR",
      "opt out",
    ],
  },
  {
    id: "runtime.cliPath",
    section: "runtime",
    tab: "cli",
    anchorId: "settings-anchor-cliPath",
    labelKey: "settings.cliPath",
    descKeys: ["settings.cliPathDesc"],
    keywords: ["cli", "binary", "grok path", "path"],
  },
  {
    id: "runtime.allowUnverifiedCli",
    section: "runtime",
    tab: "cli",
    anchorId: "settings-anchor-allowUnverifiedCli",
    labelKey: "settings.allowUnverifiedCli",
    descKeys: ["settings.allowUnverifiedCliDesc"],
    keywords: ["checksum", "sha256", "unverified", "cli install", "trust"],
  },
  {
    id: "runtime.cliWorktreeDb",
    section: "runtime",
    tab: "cli",
    anchorId: "settings-anchor-cliWorktreeDb",
    labelKey: "settings.cliWorktreeDb.title",
    descKeys: [
      "settings.cliWorktreeDb.desc",
      "settings.cliWorktreeDb.path",
      "settings.cliWorktreeDb.stats",
      "settings.cliWorktreeDb.rebuild",
      "settings.cliWorktreeDb.rebuildDesc",
    ],
    keywords: [
      "worktree db",
      "worktrees.db",
      "cli worktree",
      "db rebuild",
      "db stats",
      "db path",
      "grok worktree db",
      "0.2.117",
      "worktree index",
      "worktree 数据库",
      "worktree 資料庫",
      "重建",
    ],
  },
  {
    id: "runtime.cliUpdate",
    section: "runtime",
    tab: "cli",
    anchorId: "settings-anchor-cliUpdate",
    labelKey: "settings.cliUpdate",
    descKeys: [
      "settings.cliUpdateDesc",
      "settings.cliChannel.switchHint",
      "settings.cliChannel.pinHint",
    ],
    keywords: [
      "cli update",
      "grok update",
      "channel",
      "alpha",
      "stable",
      "version pin",
      "0.2.117",
    ],
  },
  {
    id: "runtime.proxy",
    section: "runtime",
    tab: "network",
    anchorId: "settings-anchor-proxy",
    labelKey: "settings.proxyMode",
    descKeys: [
      "settings.proxyModeDesc",
      "settings.proxyUrl",
      "settings.proxyUrlDesc",
      "settings.proxyNoProxy",
      "settings.proxyNoProxyDesc",
      "settings.proxyRestartHint",
      "settings.proxy.apply.saved",
      "settings.proxy.apply.newAgents",
      "settings.proxy.apply.reconnect",
      "settings.proxy.apply.probeEffective",
      "settings.proxy.apply.manualInvalidInherit",
      "settings.proxyUrlError.empty",
      "settings.proxyUrlError.missingScheme",
      "settings.netProbe",
      "settings.netProbeDesc",
      "settings.netProbeHonesty",
      "settings.netProbe.outcome.allOk",
      "settings.netProbe.outcome.partial",
      "settings.netProbe.outcome.allFail",
    ],
    keywords: [
      "proxy",
      "network",
      "HTTP_PROXY",
      "HTTPS_PROXY",
      "ALL_PROXY",
      "NO_PROXY",
      "socks5",
      "socks5h",
      "system proxy",
      "manual proxy",
      "direct",
      "no proxy",
      "connectivity",
      "net probe",
      "network probe",
      "bypass",
      "代理",
      "網路",
      "网络",
      "直連",
      "直连",
      "連通",
      "连通",
      "socks",
      "system",
      "manual",
    ],
  },
  {
    id: "runtime.acp",
    section: "runtime",
    tab: "connection",
    anchorId: "settings-anchor-acpServer",
    labelKey: "settings.acpServer",
    descKeys: [
      "settings.acpServerDesc",
      "settings.acpServerModeHelp",
      "settings.acpServerLocalHint",
      "settings.acpServerServeLink",
      "settings.acpTest",
      "settings.acpProbeOk",
      "settings.acpProbeFail",
    ],
    keywords: [
      "acp",
      "remote agent",
      "host port",
      "tcp",
      "api mode",
      "probe",
      "test connection",
      "health",
      "latency",
      "ws://",
      "host:port",
      "local cli",
      "agent serve",
      "连通",
      "连通性",
      "测试连接",
      "健康检查",
      "API 模式",
      "本机 CLI",
      "本機 CLI",
      "遠端",
      "远程",
    ],
  },
  {
    id: "runtime.leaderServe",
    section: "runtime",
    tab: "connection",
    anchorId: "settings-anchor-leaderServe",
    labelKey: "settings.leader.title",
    descKeys: [
      "settings.leader.desc",
      "settings.leader.start",
      "settings.leader.stop",
      "settings.leader.socket",
      "settings.leader.fleetTitle",
      "settings.leader.fleetDesc",
      "settings.leader.info",
      "settings.leader.honesty.useLeaderNotRunning",
      "settings.leader.err.socketStale",
      "settings.useLeader",
      "settings.serve.title",
      "settings.serve.desc",
      "settings.serve.start",
      "settings.serve.stop",
      "settings.serve.bind",
      "settings.serve.secret",
      "settings.serve.remote",
      "settings.serve.connectionTemplate",
    ],
    keywords: [
      "leader",
      "agent leader",
      "leader.sock",
      "shared backend",
      "socket",
      "leader list",
      "leader info",
      "leader kill",
      "fleet",
      "stale socket",
      "soft-fail",
      "use leader",
      "reachable",
      "websocket",
      "2419",
      "server-key",
      "bind",
      "secret",
      "remote",
      "--remote",
      "proxy",
      "共享后端",
      "共用後端",
      "套接字",
      "陈旧",
      "陳舊",
      "监听",
      "密鑰",
      "密钥",
      "详情",
      "詳情",
    ],
  },
  {
    id: "runtime.agentServe",
    section: "runtime",
    tab: "connection",
    anchorId: "settings-anchor-agentServe",
    labelKey: "settings.serve.title",
    descKeys: [
      "settings.serve.desc",
      "settings.serve.start",
      "settings.serve.stop",
      "settings.serve.bind",
      "settings.serve.secret",
      "settings.serve.remote",
      "settings.serve.connectionTemplate",
      "settings.serve.copyUrl",
      "settings.serve.copyCli",
      "settings.serve.healthNote",
      "settings.sdkConnect.title",
      "settings.sdkConnect.desc",
    ],
    keywords: [
      "serve",
      "agent serve",
      "websocket",
      "ws",
      "2419",
      "bind",
      "secret",
      "server-key",
      "connection url",
      "connection string",
      "--remote",
      "remote",
      "proxy",
      "ACP server",
      "sdk",
      "curl",
      "websocat",
      "remote serve",
      "tcp health",
      "远程",
      "遠端",
    ],
  },
  {
    id: "runtime.sdkConnect",
    section: "runtime",
    tab: "connection",
    anchorId: "settings-anchor-sdkConnect",
    labelKey: "settings.sdkConnect.title",
    descKeys: [
      "settings.sdkConnect.desc",
      "settings.sdkConnect.step1",
      "settings.sdkConnect.step2",
      "settings.sdkConnect.step3",
      "settings.sdkConnect.step4",
      "settings.sdkConnect.step5",
      "settings.serve.start",
      "settings.serve.secret",
    ],
    keywords: [
      "sdk connect",
      "sdk",
      "external client",
      "agent serve",
      "websocket",
      "curl",
      "websocat",
      "probe",
      "tcp",
      "server-key",
      "remote url",
      "外接",
      "探针",
      "探針",
    ],
  },
  {
    id: "runtime.maxConcurrent",
    section: "runtime",
    tab: "pool",
    anchorId: "settings-anchor-maxConcurrentAgents",
    labelKey: "settings.maxConcurrentAgents",
    descKeys: ["settings.maxConcurrentAgentsDesc"],
    keywords: ["concurrent", "pool", "parallel agents"],
  },
  {
    id: "runtime.processBudget",
    section: "runtime",
    tab: "pool",
    anchorId: "settings-anchor-processBudget",
    labelKey: "processBudget.title",
    descKeys: [
      "processBudget.lead",
      "processBudget.plan.headroom",
      "processBudget.plan.atCapBusy",
    ],
    keywords: [
      "process budget",
      "occupancy",
      "warm agents",
      "parked",
      "background",
      "process limit",
      "PROCESS_LIMIT",
      "reclaim",
      "slot",
      "并发",
      "並發",
      "进程池",
      "行程池",
      "占用",
      "佔用",
      "回收",
      "闲置",
      "閒置",
    ],
  },
  {
    id: "runtime.idle",
    section: "runtime",
    tab: "pool",
    anchorId: "settings-anchor-agentIdleMinutes",
    labelKey: "settings.agentIdleMinutes",
    descKeys: ["settings.agentIdleMinutesDesc"],
    keywords: ["idle", "recycle"],
  },
  {
    id: "runtime.stall",
    section: "runtime",
    tab: "pool",
    anchorId: "settings-anchor-streamStallSeconds",
    labelKey: "settings.streamStallSeconds",
    descKeys: ["settings.streamStallSecondsDesc"],
    keywords: ["stall", "timeout", "stream"],
  },
  {
    id: "runtime.includePartialMessages",
    section: "runtime",
    tab: "pool",
    anchorId: "settings-anchor-includePartialMessages",
    labelKey: "settings.includePartialMessages",
    descKeys: ["settings.includePartialMessagesDesc"],
    keywords: [
      "partial stream",
      "include-partial-messages",
      "stream_event",
      "streaming-messages-json",
      "partial messages",
      "headless stream",
      "增量流",
      "部分流式",
      "partial",
    ],
  },
  {
    id: "runtime.workflows",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-workflows",
    labelKey: "settings.workflows",
    descKeys: [
      "settings.workflowsDesc",
      "settings.workflowsHonesty",
      "settings.workflows.runHonesty",
      "settings.workflows.openDocs",
      "settings.workflows.discovered",
      "settings.workflows.noneFound",
      "settings.workflows.run.smoke",
      "settings.workflows.run.launch",
    ],
    keywords: [
      "workflows",
      "workflow",
      "workflows_enabled",
      "rhai",
      "create-workflow",
      "/workflows",
      "/workflow",
      "orchestration",
      "multi-agent pipeline",
      "validate_only",
      "smoke",
      "headless",
      "workflow tool",
      "工作流",
      "工作流程",
      "冒烟",
      "冒煙",
    ],
  },
  {
    id: "runtime.doctor",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-doctor",
    labelKey: "doctor.title",
    descKeys: ["settings.doctorDesc", "settings.runDoctor"],
    keywords: ["doctor", "diagnose"],
  },
  {
    id: "runtime.traces",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-traces",
    labelKey: "session.tracesTitle",
    descKeys: [
      "session.tracesDesc",
      "session.exportTraceLocal",
      "session.exportTraceUpload",
    ],
    keywords: [
      "trace",
      "traces",
      "session trace",
      "grok trace",
      "export history",
      "诊断",
      "追踪",
    ],
  },
  {
    id: "runtime.reliability",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-reliability",
    labelKey: "reliability.title",
    descKeys: [
      "reliability.settingsDesc",
      "reliability.openFromSettings",
      "reliability.audit.title",
      "reliability.audit.lead",
    ],
    keywords: [
      "reliability",
      "observability",
      "busy",
      "stall",
      "error deck",
      "support zip",
      "audit",
      "ledger",
      "tool audit",
      "permission log",
      "审计",
      "帳本",
      "账本",
      "稽核",
    ],
  },
  {
    id: "runtime.auditRetention",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-auditRetention",
    labelKey: "reliability.audit.retention",
    descKeys: [
      "reliability.audit.retentionDesc",
      "reliability.audit.retention.7",
      "reliability.audit.retention.30",
      "reliability.audit.retention.90",
      "reliability.audit.retention.unlimited",
    ],
    keywords: [
      "audit",
      "ledger",
      "retention",
      "prune",
      "tool audit",
      "permission log",
      "7 days",
      "30 days",
      "90 days",
      "unlimited",
      "保留",
      "留存",
      "清理",
      "审计",
      "帳本",
      "账本",
      "稽核",
    ],
  },
  {
    id: "runtime.batchAgents",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-batch-agents",
    labelKey: "batchAgents.title",
    descKeys: [
      "batchAgents.settingsDesc",
      "batchAgents.openFromSettings",
      "batchAgents.hint",
    ],
    keywords: [
      "batch",
      "batch agents",
      "multi project",
      "multi-project",
      "dispatch",
      "fan out",
      "headless summary",
      "same prompt",
      "批量",
      "多项目",
      "派发",
    ],
  },
  {
    id: "runtime.costRollup",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-cost-rollup",
    labelKey: "costRollup.title",
    descKeys: [
      "costRollup.settingsDesc",
      "costRollup.disclaimer",
      "costRollup.exportCopy",
      "costRollup.clearFilters",
      "costRollup.clear",
    ],
    keywords: [
      "cost",
      "rollup",
      "token usage",
      "estimate",
      "billing",
      "project cost",
      "session cost",
      "export summary",
      "filter",
      "clear samples",
      "费用",
      "费用汇总",
      "用量",
      "token",
      "会话费用",
      "筛选",
      "清除样本",
      "匯出",
      "篩選",
    ],
  },
  {
    id: "runtime.streamingMessagesJson",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-smj",
    labelKey: "smj.title",
    descKeys: ["smj.settingsDesc", "smj.lead", "smj.formatHint"],
    keywords: [
      "streaming-messages-json",
      "streaming messages",
      "ndjson",
      "output-format",
      "anthropic messages",
      "tool_use",
      "headless probe",
      "0.2.117",
      "流式消息",
      "消息 JSON",
    ],
  },
  {
    id: "runtime.streamAcpNdjson",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-stream-acp-ndjson",
    labelKey: "streamAcpNdjson.title",
    descKeys: [
      "streamAcpNdjson.settingsDesc",
      "streamAcpNdjson.lead",
    ],
    keywords: [
      "streaming-json",
      "streaming-messages-json",
      "ndjson",
      "acp",
      "session/update",
      "headless probe",
      "diagnostics",
      "0.2.117",
      "output-format",
      "诊断",
      "流式",
    ],
  },
  {
    id: "runtime.inspect",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-inspect",
    labelKey: "inspect.title",
    descKeys: ["inspect.desc"],
    keywords: ["inspect", "project inspect"],
  },
  {
    id: "runtime.prHub",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-prHub",
    labelKey: "prHub.title",
    descKeys: ["prHub.desc"],
    keywords: [
      "pull request",
      "pull requests",
      "PR",
      "PRs",
      "gh pr",
      "github pr",
      "checks",
      "comments",
      "reviews",
      "conversation",
      "mergeable",
      "CI",
      "PR hub",
      "拉取请求",
      "拉取請求",
      "合并",
      "合併",
      "评论",
      "評論",
      "检查",
      "檢查",
    ],
  },
  {
    id: "runtime.managedSetup",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-managedSetup",
    labelKey: "managedSetup.title",
    descKeys: [
      "managedSetup.desc",
      "managedSetup.authHint",
      "managedSetup.statusTitle",
      "managedSetup.sigHint",
      "managedSetup.sig.cardTitle",
      "managedSetup.recovery.presentUnverified",
    ],
    keywords: [
      "managed setup",
      "grok setup",
      "managed_config",
      "managed config",
      "deployment key",
      "GROK_DEPLOYMENT_KEY",
      "signature",
      "signature verified",
      "present unverified",
      "presence only",
      "managed_config.sig",
      "requirements.toml",
      "verify_ok",
      "托管",
      "託管",
      "部署密钥",
      "部署金鑰",
      "签名",
      "簽名",
      "验签",
      "驗簽",
      "仅存在性",
      "僅存在性",
    ],
  },
  // ── remote_im (Remote control) ──
  {
    id: "remote_im.root",
    section: "remote_im",
    tab: "im",
    anchorId: "settings-anchor-remote-im",
    labelKey: "settings.tab.remoteIm",
    descKeys: ["settings.nav.remoteIm", "settings.remoteIm.bridgeOverview"],
    keywords: [
      "remote control",
      "remote im",
      "feishu",
      "lark",
      "telegram",
      "discord",
      "bot token",
      "message content intent",
      "gateway",
      "qq",
      "onebot",
      "napcat",
      "forward websocket",
      "matrix",
      "homeserver",
      "access token",
      "sync",
      "weibo",
      "微博",
      "app_id",
      "app_secret",
      "websocket",
      "qqbot",
      "qq official",
      "official bot",
      "gateway",
      "interaction",
      "bridge",
      "im",
      "远程控制",
      "远程 IM",
      "机器人令牌",
      "正向 WebSocket",
      "访问令牌",
      "存取權杖",
      "QQ 官方",
      "官方机器人",
    ],
  },
  {
    id: "remote_im.mirror",
    section: "remote_im",
    tab: "mirror",
    anchorId: "settings-anchor-phone-mirror",
    labelKey: "settings.tab.phoneMirror",
    descKeys: [
      "mirror.connect",
      "mirror.connectTitle",
      "mirror.connectHint",
      "mirror.maxClients",
      "mirror.write.categoriesTitle",
      "mirror.rotate",
      "mirror.phase.softLocal",
      "mirror.softLocalBanner",
      "mirror.err.cloudflaredMissing",
      "settings.nav.remoteIm",
    ],
    keywords: [
      "phone mirror",
      "connect phone",
      "connect device",
      "qr",
      "cloudflared",
      "docker",
      "docker desktop",
      "max clients",
      "rotate token",
      "write allowlist",
      "tunnel",
      "soft fail",
      "soft-fail",
      "local only",
      "reconnecting",
      "手机镜像",
      "连接手机",
      "连接设备",
      "最大连接",
      "重新生成",
      "隧道",
      "仅本机",
      "软失败",
    ],
  },
  // ── shortcuts ──
  {
    id: "shortcuts.table",
    section: "shortcuts",
    anchorId: "settings-anchor-shortcuts",
    labelKey: "settings.shortcuts.title",
    descKeys: [
      "settings.shortcuts.desc",
      "settings.shortcuts.group.workbench",
      "settings.shortcuts.group.navigation",
      "settings.shortcuts.group.diagnostics",
      "settings.shortcuts.group.input",
      "settings.shortcuts.record",
      "settings.shortcuts.resetAll",
      "settings.shortcuts.resetAllTitle",
      "settings.shortcuts.filterPlaceholder",
      "settings.shortcuts.conflictsTitle",
      "settings.shortcuts.ignoreCrossScope",
      "settings.shortcuts.scope.global",
      "settings.shortcuts.scope.chatFocus",
    ],
    keywords: [
      "keyboard",
      "hotkey",
      "shortcut",
      "remap",
      "binding",
      "record",
      "filter",
      "search",
      "conflict",
      "reset all",
      "scope",
      "global",
      "chat-focus",
      "chord",
      "keymap",
      "改键",
      "快捷键",
      "录制",
      "筛选",
      "冲突",
      "全部重置",
      "范围",
      "改鍵",
      "快捷鍵",
      "錄製",
      "篩選",
      "衝突",
      "全部重設",
      "範圍",
    ],
  },
  // ── about ──
  {
    id: "about.app",
    section: "about",
    anchorId: "settings-anchor-about",
    labelKey: "settings.aboutApp",
    keywords: ["about", "version", "update"],
  },
  {
    id: "about.cli",
    section: "about",
    anchorId: "settings-anchor-aboutCli",
    labelKey: "settings.cliUpdate",
    descKeys: [
      "settings.cliUpdateDesc",
      "settings.cliChannel.switchHint",
      "settings.cliChannel.pinLabel",
    ],
    keywords: [
      "cli",
      "grok update",
      "channel",
      "alpha",
      "stable",
      "cli version",
    ],
  },
  {
    id: "about.tutorial",
    section: "about",
    anchorId: "settings-anchor-tutorial",
    labelKey: "tutorial.replay",
    descKeys: ["tutorial.replayDesc", "tutorial.menu"],
    keywords: [
      "tutorial",
      "product tour",
      "onboarding",
      "walkthrough",
      "help",
      "guide",
    ],
  },
];

export type SettingsLocation = {
  section: SettingsSectionId;
  tab?: SettingsTabId | null;
  anchorId?: string | null;
};

export function getNavDef(section: SettingsSectionId): SettingsNavDef | undefined {
  return SETTINGS_NAV.find((n) => n.id === section);
}

export function defaultTabFor(section: SettingsSectionId): SettingsTabId | null {
  const nav = getNavDef(section);
  if (!nav || nav.tabs.length === 0) return null;
  return nav.defaultTab ?? nav.tabs[0]!.id;
}

export function isValidTab(
  section: SettingsSectionId,
  tab: string | null | undefined,
): tab is SettingsTabId {
  if (!tab) return false;
  const nav = getNavDef(section);
  return !!nav?.tabs.some((t) => t.id === tab);
}

/** Resolve tab for a section: valid tab, else default, else null. */
export function resolveTab(
  section: SettingsSectionId,
  tab?: string | null,
): SettingsTabId | null {
  if (isValidTab(section, tab)) return tab;
  return defaultTabFor(section);
}

/**
 * Parse hash path after leading #/  e.g. "settings/extensions/mcp"
 * Also accepts "settings" alone.
 * Query strings (`?pr=42`) are ignored for section/tab resolution —
 * see `prHubDeepLink` for PR-hub query parsing.
 */
export function parseSettingsHash(raw: string): SettingsLocation | null {
  // Strip query so `#/settings/runtime/tools?pr=1` still resolves tools.
  const withoutQuery = raw.replace(/\?.*$/, "");
  const path = withoutQuery.replace(/^#\/?/, "").replace(/\/+$/, "");
  if (!path.startsWith("settings")) return null;
  const parts = path.split("/").filter(Boolean);
  // parts[0] === "settings"
  const sectionPart = parts[1];
  const tabPart = parts[2];
  const section: SettingsSectionId = isSettingsSectionId(sectionPart)
    ? sectionPart
    : "general";
  const tab = resolveTab(section, tabPart);
  return { section, tab };
}

/** Build hash without leading # — App adds # when writing location.hash. */
export function buildSettingsHash(loc: SettingsLocation): string {
  const section = isSettingsSectionId(loc.section) ? loc.section : "general";
  const tab = resolveTab(section, loc.tab);
  if (tab) return `#/settings/${section}/${tab}`;
  return `#/settings/${section}`;
}

/** Aggregate i18n keys used for section-level nav filtering (legacy search). */
export function keywordKeysForSection(section: SettingsSectionId): MessageKey[] {
  const keys = new Set<MessageKey>();
  const nav = getNavDef(section);
  if (nav) keys.add(nav.labelKey);
  for (const t of nav?.tabs ?? []) keys.add(t.labelKey);
  for (const e of SETTINGS_ENTRIES) {
    if (e.section !== section) continue;
    keys.add(e.labelKey);
    for (const k of e.descKeys ?? []) keys.add(k);
  }
  return [...keys];
}

export type SettingsSearchHit = {
  entry: SettingsEntry;
  /** Precomputed path label keys for UI: section · tab */
  sectionLabelKey: MessageKey;
  tabLabelKey?: MessageKey;
};

/**
 * Search entries by query against translated label/desc + raw keywords.
 * `translate` should resolve MessageKey → string for the active locale;
 * callers typically also pass an English translator for bilingual match.
 */
export function searchSettingsEntries(
  query: string,
  translate: (key: MessageKey) => string,
  translateEn?: (key: MessageKey) => string,
): SettingsSearchHit[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const en = translateEn ?? translate;
  const hits: SettingsSearchHit[] = [];
  for (const entry of SETTINGS_ENTRIES) {
    const hay: string[] = [
      entry.id,
      translate(entry.labelKey),
      en(entry.labelKey),
      ...(entry.keywords ?? []),
    ];
    for (const k of entry.descKeys ?? []) {
      hay.push(translate(k), en(k));
    }
    if (!hay.some((h) => h.toLowerCase().includes(q))) continue;
    const nav = getNavDef(entry.section);
    const tabDef = entry.tab
      ? nav?.tabs.find((t) => t.id === entry.tab)
      : undefined;
    hits.push({
      entry,
      sectionLabelKey: nav?.labelKey ?? "settings.nav.general",
      tabLabelKey: tabDef?.labelKey,
    });
  }
  return hits;
}

/** Invariant checks used by unit tests. */
export function catalogInvariants(): string[] {
  const errors: string[] = [];
  const navIds = new Set<string>();
  for (const n of SETTINGS_NAV) {
    if (navIds.has(n.id)) errors.push(`duplicate nav section: ${n.id}`);
    navIds.add(n.id);
    const tabIds = new Set<string>();
    for (const t of n.tabs) {
      if (tabIds.has(t.id)) errors.push(`duplicate tab ${t.id} in ${n.id}`);
      tabIds.add(t.id);
    }
    if (n.defaultTab && !tabIds.has(n.defaultTab)) {
      errors.push(`defaultTab ${n.defaultTab} missing in ${n.id}`);
    }
    if (n.tabs.length > 0 && !n.defaultTab) {
      errors.push(`section ${n.id} has tabs but no defaultTab`);
    }
  }
  for (const id of SETTINGS_SECTION_IDS) {
    if (!navIds.has(id)) errors.push(`section id missing from NAV: ${id}`);
  }
  const entryIds = new Set<string>();
  const anchors = new Set<string>();
  for (const e of SETTINGS_ENTRIES) {
    if (entryIds.has(e.id)) errors.push(`duplicate entry id: ${e.id}`);
    entryIds.add(e.id);
    if (anchors.has(e.anchorId)) errors.push(`duplicate anchor: ${e.anchorId}`);
    anchors.add(e.anchorId);
    if (!navIds.has(e.section)) {
      errors.push(`entry ${e.id} unknown section ${e.section}`);
    }
    if (e.tab && !isValidTab(e.section, e.tab)) {
      errors.push(`entry ${e.id} invalid tab ${e.tab} for ${e.section}`);
    }
  }
  return errors;
}
